### ISSUE TITLE
:sparkles: **E10 Class Website Checklist** :sparkles:

### ISSUE THREAD

**Issue by evangdesigns** [nss-evening-cohort-10/E10-Website#1]
- [x] **About Section**
  - [x] Needs Copy #17 
- [x] **Developers Section**
  - [x] Need student data file with: #2 
  - [x] Build and deliver cards to the DOM #3
- [x] **Technologies Section**
  - [x] Need icon data file #4
    - [x] Icons made and saved inside project
  - [x] Build and deliver icons to the DOM #5
- [x] **Thanks Section**
  - [x] Zoe, Greg, & Michael Copy #7
  - [x] Nathan, Martin, & Jameka Copy #8
  - [x] Thanks Kristin & Ashley Copy #9
  - [x] Thanks Alumni Copy #10
  - [x] Thanks John Wark Copy #11

- [ ] **CRON JOB/Zombify** #6

- [ ] **DEPLOY**

**Comment by evangdesigns** [comment]
![siteMockUp_1](https://user-images.githubusercontent.com/26425684/84729327-0b9cd880-af59-11ea-992a-a83f223f0170.jpg)
